/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRdoIndexRouteImport } from './routes/_authenticated/rdo.index'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras.index'
import { Route as AuthenticatedRdoNovoRouteImport } from './routes/_authenticated/rdo.novo'
import { Route as AuthenticatedObrasObraIdRouteImport } from './routes/_authenticated/obras.$obraId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRdoIndexRoute = AuthenticatedRdoIndexRouteImport.update({
  id: '/rdo/',
  path: '/rdo/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRdoNovoRoute = AuthenticatedRdoNovoRouteImport.update({
  id: '/rdo/novo',
  path: '/rdo/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasObraIdRoute =
  AuthenticatedObrasObraIdRouteImport.update({
    id: '/obras/$obraId',
    path: '/obras/$obraId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/obras/': typeof AuthenticatedObrasIndexRoute
  '/rdo/': typeof AuthenticatedRdoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/rdo': typeof AuthenticatedRdoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/_authenticated/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
  '/_authenticated/rdo/': typeof AuthenticatedRdoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/obras/$obraId'
    | '/rdo/novo'
    | '/obras/'
    | '/rdo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/obras/$obraId'
    | '/rdo/novo'
    | '/obras'
    | '/rdo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/obras/$obraId'
    | '/_authenticated/rdo/novo'
    | '/_authenticated/obras/'
    | '/_authenticated/rdo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rdo/': {
      id: '/_authenticated/rdo/'
      path: '/rdo'
      fullPath: '/rdo/'
      preLoaderRoute: typeof AuthenticatedRdoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rdo/novo': {
      id: '/_authenticated/rdo/novo'
      path: '/rdo/novo'
      fullPath: '/rdo/novo'
      preLoaderRoute: typeof AuthenticatedRdoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId': {
      id: '/_authenticated/obras/$obraId'
      path: '/obras/$obraId'
      fullPath: '/obras/$obraId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedObrasObraIdRoute: typeof AuthenticatedObrasObraIdRoute
  AuthenticatedRdoNovoRoute: typeof AuthenticatedRdoNovoRoute
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
  AuthenticatedRdoIndexRoute: typeof AuthenticatedRdoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedObrasObraIdRoute: AuthenticatedObrasObraIdRoute,
  AuthenticatedRdoNovoRoute: AuthenticatedRdoNovoRoute,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
  AuthenticatedRdoIndexRoute: AuthenticatedRdoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
