/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as InstalarRouteImport } from './routes/instalar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedGaleriaRouteImport } from './routes/_authenticated/galeria'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedRdoIndexRouteImport } from './routes/_authenticated/rdo.index'
import { Route as AuthenticatedObrasIndexRouteImport } from './routes/_authenticated/obras.index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes.index'
import { Route as AuthenticatedCadastrosIndexRouteImport } from './routes/_authenticated/cadastros.index'
import { Route as AuthenticatedRelatoriosDimRouteImport } from './routes/_authenticated/relatorios.$dim'
import { Route as AuthenticatedRdoNovoRouteImport } from './routes/_authenticated/rdo.novo'
import { Route as AuthenticatedRdoRdoIdRouteImport } from './routes/_authenticated/rdo.$rdoId'
import { Route as AuthenticatedObrasObraIdRouteImport } from './routes/_authenticated/obras.$obraId'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes.usuarios'
import { Route as AuthenticatedConfiguracoesSkeletonRouteImport } from './routes/_authenticated/configuracoes.skeleton'
import { Route as AuthenticatedConfiguracoesSistemaRouteImport } from './routes/_authenticated/configuracoes.sistema'
import { Route as AuthenticatedConfiguracoesPermissoesRouteImport } from './routes/_authenticated/configuracoes.permissoes'
import { Route as AuthenticatedConfiguracoesOnedriveRouteImport } from './routes/_authenticated/configuracoes.onedrive'
import { Route as AuthenticatedConfiguracoesGruposRouteImport } from './routes/_authenticated/configuracoes.grupos'
import { Route as AuthenticatedConfiguracoesAuditoriaRouteImport } from './routes/_authenticated/configuracoes.auditoria'
import { Route as AuthenticatedConfiguracoesAplicativoRouteImport } from './routes/_authenticated/configuracoes.aplicativo'
import { Route as AuthenticatedCadastrosOcorrenciasRouteImport } from './routes/_authenticated/cadastros.ocorrencias'
import { Route as AuthenticatedCadastrosMaoDeObraRouteImport } from './routes/_authenticated/cadastros.mao-de-obra'
import { Route as AuthenticatedCadastrosEquipamentosRouteImport } from './routes/_authenticated/cadastros.equipamentos'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InstalarRoute = InstalarRouteImport.update({
  id: '/instalar',
  path: '/instalar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedGaleriaRoute = AuthenticatedGaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRdoIndexRoute = AuthenticatedRdoIndexRouteImport.update({
  id: '/rdo/',
  path: '/rdo/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasIndexRoute = AuthenticatedObrasIndexRouteImport.update({
  id: '/obras/',
  path: '/obras/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedCadastrosIndexRoute =
  AuthenticatedCadastrosIndexRouteImport.update({
    id: '/cadastros/',
    path: '/cadastros/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRelatoriosDimRoute =
  AuthenticatedRelatoriosDimRouteImport.update({
    id: '/relatorios/$dim',
    path: '/relatorios/$dim',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRdoNovoRoute = AuthenticatedRdoNovoRouteImport.update({
  id: '/rdo/novo',
  path: '/rdo/novo',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRdoRdoIdRoute = AuthenticatedRdoRdoIdRouteImport.update({
  id: '/rdo/$rdoId',
  path: '/rdo/$rdoId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedObrasObraIdRoute =
  AuthenticatedObrasObraIdRouteImport.update({
    id: '/obras/$obraId',
    path: '/obras/$obraId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesSkeletonRoute =
  AuthenticatedConfiguracoesSkeletonRouteImport.update({
    id: '/skeleton',
    path: '/skeleton',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesSistemaRoute =
  AuthenticatedConfiguracoesSistemaRouteImport.update({
    id: '/sistema',
    path: '/sistema',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesPermissoesRoute =
  AuthenticatedConfiguracoesPermissoesRouteImport.update({
    id: '/permissoes',
    path: '/permissoes',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesOnedriveRoute =
  AuthenticatedConfiguracoesOnedriveRouteImport.update({
    id: '/onedrive',
    path: '/onedrive',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesGruposRoute =
  AuthenticatedConfiguracoesGruposRouteImport.update({
    id: '/grupos',
    path: '/grupos',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesAuditoriaRoute =
  AuthenticatedConfiguracoesAuditoriaRouteImport.update({
    id: '/auditoria',
    path: '/auditoria',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedConfiguracoesAplicativoRoute =
  AuthenticatedConfiguracoesAplicativoRouteImport.update({
    id: '/aplicativo',
    path: '/aplicativo',
    getParentRoute: () => AuthenticatedConfiguracoesRoute,
  } as any)
const AuthenticatedCadastrosOcorrenciasRoute =
  AuthenticatedCadastrosOcorrenciasRouteImport.update({
    id: '/cadastros/ocorrencias',
    path: '/cadastros/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosMaoDeObraRoute =
  AuthenticatedCadastrosMaoDeObraRouteImport.update({
    id: '/cadastros/mao-de-obra',
    path: '/cadastros/mao-de-obra',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCadastrosEquipamentosRoute =
  AuthenticatedCadastrosEquipamentosRouteImport.update({
    id: '/cadastros/equipamentos',
    path: '/cadastros/equipamentos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/mao-de-obra': typeof AuthenticatedCadastrosMaoDeObraRoute
  '/cadastros/ocorrencias': typeof AuthenticatedCadastrosOcorrenciasRoute
  '/configuracoes/aplicativo': typeof AuthenticatedConfiguracoesAplicativoRoute
  '/configuracoes/auditoria': typeof AuthenticatedConfiguracoesAuditoriaRoute
  '/configuracoes/grupos': typeof AuthenticatedConfiguracoesGruposRoute
  '/configuracoes/onedrive': typeof AuthenticatedConfiguracoesOnedriveRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/configuracoes/skeleton': typeof AuthenticatedConfiguracoesSkeletonRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/rdo/$rdoId': typeof AuthenticatedRdoRdoIdRoute
  '/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/relatorios/$dim': typeof AuthenticatedRelatoriosDimRoute
  '/cadastros/': typeof AuthenticatedCadastrosIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/obras/': typeof AuthenticatedObrasIndexRoute
  '/rdo/': typeof AuthenticatedRdoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/galeria': typeof AuthenticatedGaleriaRoute
  '/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/cadastros/mao-de-obra': typeof AuthenticatedCadastrosMaoDeObraRoute
  '/cadastros/ocorrencias': typeof AuthenticatedCadastrosOcorrenciasRoute
  '/configuracoes/aplicativo': typeof AuthenticatedConfiguracoesAplicativoRoute
  '/configuracoes/auditoria': typeof AuthenticatedConfiguracoesAuditoriaRoute
  '/configuracoes/grupos': typeof AuthenticatedConfiguracoesGruposRoute
  '/configuracoes/onedrive': typeof AuthenticatedConfiguracoesOnedriveRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/configuracoes/skeleton': typeof AuthenticatedConfiguracoesSkeletonRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/rdo/$rdoId': typeof AuthenticatedRdoRdoIdRoute
  '/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/relatorios/$dim': typeof AuthenticatedRelatoriosDimRoute
  '/cadastros': typeof AuthenticatedCadastrosIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/obras': typeof AuthenticatedObrasIndexRoute
  '/rdo': typeof AuthenticatedRdoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/instalar': typeof InstalarRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/galeria': typeof AuthenticatedGaleriaRoute
  '/_authenticated/cadastros/equipamentos': typeof AuthenticatedCadastrosEquipamentosRoute
  '/_authenticated/cadastros/mao-de-obra': typeof AuthenticatedCadastrosMaoDeObraRoute
  '/_authenticated/cadastros/ocorrencias': typeof AuthenticatedCadastrosOcorrenciasRoute
  '/_authenticated/configuracoes/aplicativo': typeof AuthenticatedConfiguracoesAplicativoRoute
  '/_authenticated/configuracoes/auditoria': typeof AuthenticatedConfiguracoesAuditoriaRoute
  '/_authenticated/configuracoes/grupos': typeof AuthenticatedConfiguracoesGruposRoute
  '/_authenticated/configuracoes/onedrive': typeof AuthenticatedConfiguracoesOnedriveRoute
  '/_authenticated/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/_authenticated/configuracoes/sistema': typeof AuthenticatedConfiguracoesSistemaRoute
  '/_authenticated/configuracoes/skeleton': typeof AuthenticatedConfiguracoesSkeletonRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/obras/$obraId': typeof AuthenticatedObrasObraIdRoute
  '/_authenticated/rdo/$rdoId': typeof AuthenticatedRdoRdoIdRoute
  '/_authenticated/rdo/novo': typeof AuthenticatedRdoNovoRoute
  '/_authenticated/relatorios/$dim': typeof AuthenticatedRelatoriosDimRoute
  '/_authenticated/cadastros/': typeof AuthenticatedCadastrosIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/obras/': typeof AuthenticatedObrasIndexRoute
  '/_authenticated/rdo/': typeof AuthenticatedRdoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/configuracoes'
    | '/dashboard'
    | '/empresa'
    | '/galeria'
    | '/cadastros/equipamentos'
    | '/cadastros/mao-de-obra'
    | '/cadastros/ocorrencias'
    | '/configuracoes/aplicativo'
    | '/configuracoes/auditoria'
    | '/configuracoes/grupos'
    | '/configuracoes/onedrive'
    | '/configuracoes/permissoes'
    | '/configuracoes/sistema'
    | '/configuracoes/skeleton'
    | '/configuracoes/usuarios'
    | '/obras/$obraId'
    | '/rdo/$rdoId'
    | '/rdo/novo'
    | '/relatorios/$dim'
    | '/cadastros/'
    | '/configuracoes/'
    | '/obras/'
    | '/rdo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/dashboard'
    | '/empresa'
    | '/galeria'
    | '/cadastros/equipamentos'
    | '/cadastros/mao-de-obra'
    | '/cadastros/ocorrencias'
    | '/configuracoes/aplicativo'
    | '/configuracoes/auditoria'
    | '/configuracoes/grupos'
    | '/configuracoes/onedrive'
    | '/configuracoes/permissoes'
    | '/configuracoes/sistema'
    | '/configuracoes/skeleton'
    | '/configuracoes/usuarios'
    | '/obras/$obraId'
    | '/rdo/$rdoId'
    | '/rdo/novo'
    | '/relatorios/$dim'
    | '/cadastros'
    | '/configuracoes'
    | '/obras'
    | '/rdo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/instalar'
    | '/reset-password'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresa'
    | '/_authenticated/galeria'
    | '/_authenticated/cadastros/equipamentos'
    | '/_authenticated/cadastros/mao-de-obra'
    | '/_authenticated/cadastros/ocorrencias'
    | '/_authenticated/configuracoes/aplicativo'
    | '/_authenticated/configuracoes/auditoria'
    | '/_authenticated/configuracoes/grupos'
    | '/_authenticated/configuracoes/onedrive'
    | '/_authenticated/configuracoes/permissoes'
    | '/_authenticated/configuracoes/sistema'
    | '/_authenticated/configuracoes/skeleton'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/obras/$obraId'
    | '/_authenticated/rdo/$rdoId'
    | '/_authenticated/rdo/novo'
    | '/_authenticated/relatorios/$dim'
    | '/_authenticated/cadastros/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/obras/'
    | '/_authenticated/rdo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstalarRoute: typeof InstalarRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instalar': {
      id: '/instalar'
      path: '/instalar'
      fullPath: '/instalar'
      preLoaderRoute: typeof InstalarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/galeria': {
      id: '/_authenticated/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof AuthenticatedGaleriaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rdo/': {
      id: '/_authenticated/rdo/'
      path: '/rdo'
      fullPath: '/rdo/'
      preLoaderRoute: typeof AuthenticatedRdoIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/': {
      id: '/_authenticated/obras/'
      path: '/obras'
      fullPath: '/obras/'
      preLoaderRoute: typeof AuthenticatedObrasIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/cadastros/': {
      id: '/_authenticated/cadastros/'
      path: '/cadastros'
      fullPath: '/cadastros/'
      preLoaderRoute: typeof AuthenticatedCadastrosIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios/$dim': {
      id: '/_authenticated/relatorios/$dim'
      path: '/relatorios/$dim'
      fullPath: '/relatorios/$dim'
      preLoaderRoute: typeof AuthenticatedRelatoriosDimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rdo/novo': {
      id: '/_authenticated/rdo/novo'
      path: '/rdo/novo'
      fullPath: '/rdo/novo'
      preLoaderRoute: typeof AuthenticatedRdoNovoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rdo/$rdoId': {
      id: '/_authenticated/rdo/$rdoId'
      path: '/rdo/$rdoId'
      fullPath: '/rdo/$rdoId'
      preLoaderRoute: typeof AuthenticatedRdoRdoIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/obras/$obraId': {
      id: '/_authenticated/obras/$obraId'
      path: '/obras/$obraId'
      fullPath: '/obras/$obraId'
      preLoaderRoute: typeof AuthenticatedObrasObraIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/skeleton': {
      id: '/_authenticated/configuracoes/skeleton'
      path: '/skeleton'
      fullPath: '/configuracoes/skeleton'
      preLoaderRoute: typeof AuthenticatedConfiguracoesSkeletonRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/sistema': {
      id: '/_authenticated/configuracoes/sistema'
      path: '/sistema'
      fullPath: '/configuracoes/sistema'
      preLoaderRoute: typeof AuthenticatedConfiguracoesSistemaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/permissoes': {
      id: '/_authenticated/configuracoes/permissoes'
      path: '/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPermissoesRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/onedrive': {
      id: '/_authenticated/configuracoes/onedrive'
      path: '/onedrive'
      fullPath: '/configuracoes/onedrive'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOnedriveRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/grupos': {
      id: '/_authenticated/configuracoes/grupos'
      path: '/grupos'
      fullPath: '/configuracoes/grupos'
      preLoaderRoute: typeof AuthenticatedConfiguracoesGruposRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/auditoria': {
      id: '/_authenticated/configuracoes/auditoria'
      path: '/auditoria'
      fullPath: '/configuracoes/auditoria'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAuditoriaRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/configuracoes/aplicativo': {
      id: '/_authenticated/configuracoes/aplicativo'
      path: '/aplicativo'
      fullPath: '/configuracoes/aplicativo'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAplicativoRouteImport
      parentRoute: typeof AuthenticatedConfiguracoesRoute
    }
    '/_authenticated/cadastros/ocorrencias': {
      id: '/_authenticated/cadastros/ocorrencias'
      path: '/cadastros/ocorrencias'
      fullPath: '/cadastros/ocorrencias'
      preLoaderRoute: typeof AuthenticatedCadastrosOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/mao-de-obra': {
      id: '/_authenticated/cadastros/mao-de-obra'
      path: '/cadastros/mao-de-obra'
      fullPath: '/cadastros/mao-de-obra'
      preLoaderRoute: typeof AuthenticatedCadastrosMaoDeObraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cadastros/equipamentos': {
      id: '/_authenticated/cadastros/equipamentos'
      path: '/cadastros/equipamentos'
      fullPath: '/cadastros/equipamentos'
      preLoaderRoute: typeof AuthenticatedCadastrosEquipamentosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedConfiguracoesRouteChildren {
  AuthenticatedConfiguracoesAplicativoRoute: typeof AuthenticatedConfiguracoesAplicativoRoute
  AuthenticatedConfiguracoesAuditoriaRoute: typeof AuthenticatedConfiguracoesAuditoriaRoute
  AuthenticatedConfiguracoesGruposRoute: typeof AuthenticatedConfiguracoesGruposRoute
  AuthenticatedConfiguracoesOnedriveRoute: typeof AuthenticatedConfiguracoesOnedriveRoute
  AuthenticatedConfiguracoesPermissoesRoute: typeof AuthenticatedConfiguracoesPermissoesRoute
  AuthenticatedConfiguracoesSistemaRoute: typeof AuthenticatedConfiguracoesSistemaRoute
  AuthenticatedConfiguracoesSkeletonRoute: typeof AuthenticatedConfiguracoesSkeletonRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedConfiguracoesRouteChildren: AuthenticatedConfiguracoesRouteChildren =
  {
    AuthenticatedConfiguracoesAplicativoRoute:
      AuthenticatedConfiguracoesAplicativoRoute,
    AuthenticatedConfiguracoesAuditoriaRoute:
      AuthenticatedConfiguracoesAuditoriaRoute,
    AuthenticatedConfiguracoesGruposRoute:
      AuthenticatedConfiguracoesGruposRoute,
    AuthenticatedConfiguracoesOnedriveRoute:
      AuthenticatedConfiguracoesOnedriveRoute,
    AuthenticatedConfiguracoesPermissoesRoute:
      AuthenticatedConfiguracoesPermissoesRoute,
    AuthenticatedConfiguracoesSistemaRoute:
      AuthenticatedConfiguracoesSistemaRoute,
    AuthenticatedConfiguracoesSkeletonRoute:
      AuthenticatedConfiguracoesSkeletonRoute,
    AuthenticatedConfiguracoesUsuariosRoute:
      AuthenticatedConfiguracoesUsuariosRoute,
    AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
  }

const AuthenticatedConfiguracoesRouteWithChildren =
  AuthenticatedConfiguracoesRoute._addFileChildren(
    AuthenticatedConfiguracoesRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedGaleriaRoute: typeof AuthenticatedGaleriaRoute
  AuthenticatedCadastrosEquipamentosRoute: typeof AuthenticatedCadastrosEquipamentosRoute
  AuthenticatedCadastrosMaoDeObraRoute: typeof AuthenticatedCadastrosMaoDeObraRoute
  AuthenticatedCadastrosOcorrenciasRoute: typeof AuthenticatedCadastrosOcorrenciasRoute
  AuthenticatedObrasObraIdRoute: typeof AuthenticatedObrasObraIdRoute
  AuthenticatedRdoRdoIdRoute: typeof AuthenticatedRdoRdoIdRoute
  AuthenticatedRdoNovoRoute: typeof AuthenticatedRdoNovoRoute
  AuthenticatedRelatoriosDimRoute: typeof AuthenticatedRelatoriosDimRoute
  AuthenticatedCadastrosIndexRoute: typeof AuthenticatedCadastrosIndexRoute
  AuthenticatedObrasIndexRoute: typeof AuthenticatedObrasIndexRoute
  AuthenticatedRdoIndexRoute: typeof AuthenticatedRdoIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedGaleriaRoute: AuthenticatedGaleriaRoute,
  AuthenticatedCadastrosEquipamentosRoute:
    AuthenticatedCadastrosEquipamentosRoute,
  AuthenticatedCadastrosMaoDeObraRoute: AuthenticatedCadastrosMaoDeObraRoute,
  AuthenticatedCadastrosOcorrenciasRoute:
    AuthenticatedCadastrosOcorrenciasRoute,
  AuthenticatedObrasObraIdRoute: AuthenticatedObrasObraIdRoute,
  AuthenticatedRdoRdoIdRoute: AuthenticatedRdoRdoIdRoute,
  AuthenticatedRdoNovoRoute: AuthenticatedRdoNovoRoute,
  AuthenticatedRelatoriosDimRoute: AuthenticatedRelatoriosDimRoute,
  AuthenticatedCadastrosIndexRoute: AuthenticatedCadastrosIndexRoute,
  AuthenticatedObrasIndexRoute: AuthenticatedObrasIndexRoute,
  AuthenticatedRdoIndexRoute: AuthenticatedRdoIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  InstalarRoute: InstalarRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
